Fix/spellcheck
iscore-pfa/qml-remote pull request #87
Opened 2021-07-13 12:42 UTC by Toine-ddt

2021-07-16 13:40 UTC, jcelerier commented on src/IpAddress/ScoreConnection.qml
> -  * - visible when the remote is disconnected form score
no this is correct

(however I guess afterwards you mean "from score", not "form score")

2021-07-16 13:40 UTC, jcelerier requested changes
small typo

2021-07-16 14:50 UTC, Toine-ddt commented
small typo ?

2026-06-30 18:46 UTC, jcelerier commented
Fixed in main branch

2026-06-30 18:46 UTC, closed without merging